faq_items:
  - question: "What is SweatSpace?"
    answer: |
      SweatSpace is a new community for New York City-based fitness instructors and the people who love their classes. As boutique fitness studios and group classes continue to boom, there are more full-time fitness professionals than ever before. A lot of us teach at more than one studio or at least more than one location, but existing software doesn't make it easy for us to answer one of the questions we most often get asked: "When and where else do you teach?"

      After attempting to keep a website updated and spending too much time typing out our schedules in Instagram captions, we created SweatSpace. Our schedules (complete with studio info, class info, and sign up links), links to the social media networks we're most active on, and even our playlists -- all in one place.

      Stronger, better, easier connections between instructors, their students, and each other. That's SweatSpace.
  - question: "Who can join SweatSpace?"
    answer: |
      SweatSpace is currently invite-only and limited to people who teach yoga and group fitness classes in New York City. If you or someone you know is interested in joining, please reach out to us here -- someone from our team will get back to you quickly.
  - question: "How often do I need to update my schedule on SweatSpace?"
    answer: |
      We allow your schedule to be viewed one month in advance. SweatSpace makes keeping your schedule up-to-date as easy as possible -- you enter in your recurring schedule once and then easily go in and make changes when you are picking up or subbing out classes.
